### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SukramJ**
Hi @danielperna84,

i'd like to update the readme to better reflect the current state.
Is it necessary to stay with python 3.6?
Current HA supported python version is 3.9.

BR

### CODE REVIEW

**Comment by danielperna84** [comment]
Sure, we can upgrade this to whatever Home Assistant is using. 👍

**Comment by danielperna84** [comment]
> No 3rd party Python dependencies are required.

Regarding that topic: how do we handle conflicts of HA-requirements vs. hahomematic requirements? Right now we require `aiohttp==3.8.0` and HA does as well. But if the dependency gets upgraded for HA (and we may not notice that), we'd also have to build a new hahomematic release for that, which might not be necessary. I guess we could just declare the dependency as `aiohttp>=3.8.0`. Same for voluptuous. 🤷‍♂️

**Comment by SukramJ** [comment]
Good point, i fixed it.

**Comment by danielperna84** [comment]
Great. Feel free to merge when you're done. LGTM.

**Pull request merged**
