### PR TITLE
Add more devices 

### PR DESCRIPTION
**Pull request by SukramJ**
- Add KeyMatic
- Add HmIP-MOD-OC8
- Add HmIP-PCBS, HmIP-PCBS2, HmIP-PCBS-BAT, HmIP-USBSM
- Remove xmlrpc calls related to ccu system variables (not supported by api)
- Update hub sensor excludes

### CODE REVIEW

**Comment by danielperna84** [comment]
The system variable stuff via the proxy is for Homegear. Homegear has additional API methods for this because there's no JSON-RPC. Here's the API reference: https://ref.homegear.eu/rpc.html#getAllSystemVariables

**Comment by SukramJ** [comment]
I know. This is the dedicated Client for the CCU (ClientCCU). The Client for Homegear (ClientHomegear) uses the proxy version.
I missed to remove the code when i splitted the implementation.

**Comment by SukramJ** [comment]
Do you have something like "HmIP_Device_Documentation.pdf" for the  Bidcos-RF devices?
Currently i use pydevccu and pyhomematic as reference for Bidcos-RF.

**Comment by danielperna84** [comment]
[hm_devices_Endkunden.pdf](https://github.com/danielperna84/hahomematic/files/7627790/hm_devices_Endkunden.pdf)

Yes. But this is incomplete, as it hasn't been updated for a while. So for some devices pydevccu is the best source because I have extracted everything from the XMLs on the CCU.

**Pull request merged**
